### ISSUE TITLE
Question: Does this support javascript/typescript HMR?

### ISSUE THREAD

**Issue by aleksolutions** [collabsoft-net/dcdx#2]
Hi guys!

Thank you for sharing your solution!

Does this solution support javascript/typescript HMR?

**Comment by remie** [comment]
@aleksolutions unfortunately we have never been able to get HMR working with Atlassian Data Center products. There have been multiple threads on CDAC about it. See https://community.developer.atlassian.com/t/preparing-for-jira-software-10-0-and-jira-service-management-6-0-multiple-eaps-coming-your-way/76688/27 for the latest status and reference to the other threads

**Comment by aleksolutions** [comment]
Hi @remie, I managed to make HMR work with webpack 5 and [WRMPlugin](https://www.npmjs.com/package/atlassian-webresource-webpack-plugin). It's not pretty and it is focused to work with React, but if you want me to share the config just let me know.
